### ISSUE TITLE
Forge 1639 error

### ISSUE THREAD

**Issue by JohnRohner** [airbreather/pig-manure-mod#3] opened 2015-12-22 17:32 UTC
Server side upon start up:
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]: java.lang.IllegalStateException: Registry entry for minecr
aft:items airbreather.mods.pigmanure.ItemManure@4f1c4c40, id 4285, name pigmanur
e:manure, marked as dangling.
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.registry.FMLControlledN
amespacedRegistry.validateContent(FMLControlledNamespacedRegistry.java:144)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.registry.PersistentRegi
stryManager$ValidateRegistryFunction.apply(PersistentRegistryManager.java:549)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.registry.PersistentRegi
stryManager$ValidateRegistryFunction.apply(PersistentRegistryManager.java:542)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.registry.PersistentRegi
stryManager.forAllRegistries(PersistentRegistryManager.java:209)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.registry.PersistentRegi
stryManager.injectSnapshot(PersistentRegistryManager.java:181)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.FMLContainer.readData(F
MLContainer.java:301)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraftforge.fml.common.FMLCommonHandler.handle
WorldDataLoad(FMLCommonHandler.java:408)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraft.world.storage.SaveHandler.func_75757_d(
SaveHandler.java:116)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraft.server.MinecraftServer.func_71247_a(Min
ecraftServer.java:233)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraft.server.dedicated.DedicatedServer.func_7
1197_b(DedicatedServer.java:254)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:441)
[11:23:19] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandl
er:func_75757_d:125]:   at java.lang.Thread.run(Unknown Source)

**Comment by airbreather** [comment] 2016-02-18 13:47
Does this still happen?  If so, can you give more details about your setup?  Is this, maybe, a world that used to have Pig Manure, but now doesn't?

**Comment by airbreather** [comment] 2016-02-26 13:28
Closing this for now because there's a 1.8.9 build available and I don't have enough information to be able to reproduce.  Feel free to reopen if it happens again on the latest supported Forge version.

**Closed as completed by airbreather** 2016-02-26 13:28 UTC
